### ISSUE TITLE
Timezone information from SMHI is removed when parsing the timestamp

### ISSUE THREAD

**Issue by daha** [joysoftware/pypi_smhi#16]
The field validTime in the SMHI response include information about timezone (the Z in the end, which means UTC), example "2024-05-09T21:00:00Z". When the timestamp from the field validTime from the SMHI response is parsed that information is removed and a plain `datetime` object without timezone information is created, see code snipped below.

https://github.com/joysoftware/pypi_smhi/blob/b8b73bbf16b90b171e0866e64095d895de16a1f2/smhi/smhi_lib.py#L392C21-L392C84

The result is that anyone using this library which has a system timezone which is other than UTC will get the wrong timestamps for the forecasts as datetime assumes a timestamp is in local timezone if it does not have any timezone information. I noticed this in the SMHI addon in Home Assistant which is using this library, where the timestamps for the forecasts were 2 hours off when I am in the timezone CEST compared to the timestamps I get from the SMHI API.

**Comment by helto4real** [comment]
PR #17 merged and new release 1.0.17 is available. Sorry for being late tracking this repo.
