### ISSUE TITLE
Lost precision

### ISSUE THREAD

**Issue by techillin** [joysoftware/pypi_smhi#19]
Several data points in the SMHI API specify data type as **Decimal number, one decimal** but this library uses **Int** instead which means lost precision.

**Comment by gjohansson-ST** [comment]
I don't see anything specific when I check. Maybe you can be a bit more precise on which data points you mean are having lost precision?
As example I see `temperature` is typed as `int` but it's actually saved as `float` but I guess you have some real world issues here?

**Comment by techillin** [comment]
Home Assistant SMHI Integration only returns whole numbers
`rounded_temp = int(round(temperature))` is probably where precision is lost
