### ISSUE TITLE
Empty wheels package published

### ISSUE THREAD

**Issue by frenck** [joysoftware/pypi_smhi#2]
You have published a wheels package about 9 hours ago, this wheels package is empty.

This can cause unexpected behavior if one would install this package, since the installation would succeed, but the library itself is actually missing.

Contents of wheel package:

![image](https://user-images.githubusercontent.com/195327/77550786-ca44e180-6eb1-11ea-95d1-8efe5ee27367.png)

It currently causes the Home Assistant builds to fail since it is used for running Unit Tests.

**Comment by helto4real** [comment]
Fixed the issue with pypackage release pipeline. New version 1.0.13 is deployed. New version is merged into Home Assistant Core https://github.com/home-assistant/core/pull/33259
**Notes to myself.. Update version number before deploy new CD pipeline :)**
